// Generated list: only the brand icons Aurora maps, so the bundle stays small.
import {
  siReact,
  siNextdotjs,
  siVuedotjs,
  siSvelte,
  siAngular,
  siAstro,
  siExpo,
  siExpress,
  siFastify,
  siNestjs,
  siHono,
  siVite,
  siTypescript,
  siTailwindcss,
  siSocketdotio,
  siReactrouter,
  siReactquery,
  siRedux,
  siPrisma,
  siDrizzle,
  siVitest,
  siJest,
  siCypress,
  siEslint,
  siBiome,
  siPwa,
  siI18next,
  siThreedotjs,
  siSupabase,
  siFirebase,
  siFastapi,
  siDjango,
  siFlask,
  siSqlalchemy,
  siPydantic,
  siPytest,
  siCelery,
  siLaravel,
  siSymfony,
  siLivewire,
  siNodedotjs,
  siPython,
  siPhp,
  siNginx,
  siPostgresql,
  siMysql,
  siMariadb,
  siMongodb,
  siRedis,
  siTraefikproxy,
  siCaddy,
  siElasticsearch,
  siRabbitmq,
  siMinio,
  siDocker,
  siAlpinelinux,
  siDebian,
  siGithubactions,
  siGitlab,
  siGithub,
  siHtml5,
  siFramer,
  siLucide,
} from "simple-icons";

export type SimpleIcon = { path: string; hex: string; title: string };

export const BRANDS: Record<string, SimpleIcon> = {
  "react": siReact,
  "nextdotjs": siNextdotjs,
  "vuedotjs": siVuedotjs,
  "svelte": siSvelte,
  "angular": siAngular,
  "astro": siAstro,
  "expo": siExpo,
  "express": siExpress,
  "fastify": siFastify,
  "nestjs": siNestjs,
  "hono": siHono,
  "vite": siVite,
  "typescript": siTypescript,
  "tailwindcss": siTailwindcss,
  "socketdotio": siSocketdotio,
  "reactrouter": siReactrouter,
  "reactquery": siReactquery,
  "redux": siRedux,
  "prisma": siPrisma,
  "drizzle": siDrizzle,
  "vitest": siVitest,
  "jest": siJest,
  "cypress": siCypress,
  "eslint": siEslint,
  "biome": siBiome,
  "pwa": siPwa,
  "i18next": siI18next,
  "threedotjs": siThreedotjs,
  "supabase": siSupabase,
  "firebase": siFirebase,
  "fastapi": siFastapi,
  "django": siDjango,
  "flask": siFlask,
  "sqlalchemy": siSqlalchemy,
  "pydantic": siPydantic,
  "pytest": siPytest,
  "celery": siCelery,
  "laravel": siLaravel,
  "symfony": siSymfony,
  "livewire": siLivewire,
  "nodedotjs": siNodedotjs,
  "python": siPython,
  "php": siPhp,
  "nginx": siNginx,
  "postgresql": siPostgresql,
  "mysql": siMysql,
  "mariadb": siMariadb,
  "mongodb": siMongodb,
  "redis": siRedis,
  "traefikproxy": siTraefikproxy,
  "caddy": siCaddy,
  "elasticsearch": siElasticsearch,
  "rabbitmq": siRabbitmq,
  "minio": siMinio,
  "docker": siDocker,
  "alpinelinux": siAlpinelinux,
  "debian": siDebian,
  "githubactions": siGithubactions,
  "gitlab": siGitlab,
  "github": siGithub,
  "html5": siHtml5,
  "framer": siFramer,
  "lucide": siLucide,
};
